import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react';
import fs from 'fs';
import path from 'path';

// Load self-signed certs if they exist (generated by setup-ssl.js)
const certPath = path.resolve('ssl/cert.pem');
const keyPath = path.resolve('ssl/key.pem');
const hasCerts = fs.existsSync(certPath) && fs.existsSync(keyPath);

export default defineConfig({
  plugins: [react()],
  server: {
    port: 5174,
    host: true,
    https: hasCerts ? { key: fs.readFileSync(keyPath), cert: fs.readFileSync(certPath) } : false,
    proxy: {
      // Proxy all /api calls to the backend — avoids mixed-content block on HTTPS
      '/api': {
        target: 'http://localhost:5000',
        changeOrigin: true,
        secure: false,
      },
      // Also proxy /uploads so photo images load over HTTPS (no mixed-content block)
      '/uploads': {
        target: 'http://localhost:5000',
        changeOrigin: true,
        secure: false,
      },
    },
  },
});
